// scripts/generate-theme.mjs (ERSETZT die Slice-1-Version vollständig)
// Dieses Script ist das vollständige generate-theme.mjs nach Slice 5.
// Die Funktionen validateConfig() und generateCSS() aus Slice 1 sind hier beibehalten
// und identisch übernommen. Neu hinzugekommen ist deepMerge() sowie der erweiterte
// Main-Flow der Default-YAML und Shop-YAML lädt und merged.
import { readFileSync, writeFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { parse } from 'yaml'

const __dirname = dirname(fileURLToPath(import.meta.url))
const FRONTEND_ROOT = resolve(__dirname, '..')

const OKLCH_REGEX = /^oklch\(\s*[\d.]+\s+[\d.]+\s+[\d.]+(\s*\/\s*[\d.]+)?\s*\)$/

/**
 * Deep merges two config objects.
 * Values from override take precedence over base values.
 * Only supports one level of nesting (categories like colors, fonts, etc.).
 * @param {Record<string, any>} base
 * @param {Record<string, any>} override
 * @returns {Record<string, any>}
 */
function deepMerge(base, override) {
  const result = {}

  // Collect all keys from both objects
  const allKeys = new Set([...Object.keys(base), ...Object.keys(override)])

  for (const key of allKeys) {
    const baseVal = base[key]
    const overrideVal = override[key]

    if (
      overrideVal !== undefined &&
      overrideVal !== null &&
      typeof overrideVal === 'object' &&
      !Array.isArray(overrideVal) &&
      typeof baseVal === 'object' &&
      baseVal !== null &&
      !Array.isArray(baseVal)
    ) {
      // Both are plain objects → merge recursively (one level deep)
      result[key] = { ...baseVal, ...overrideVal }
    } else if (overrideVal !== undefined && overrideVal !== null) {
      // Override has a value → use it
      result[key] = overrideVal
    } else {
      // Only base has a value → use it
      result[key] = baseVal
    }
  }

  return result
}

/**
 * Validates a theme config object.
 * Exits with code 1 and prints error message on first validation failure.
 * @param {Record<string, any>} config
 */
function validateConfig(config) {
  if (config.colors) {
    for (const [key, value] of Object.entries(config.colors)) {
      if (typeof value !== 'string' || !OKLCH_REGEX.test(value.trim())) {
        process.stderr.write(`Invalid color format for ${key}: expected oklch()\n`)
        process.exit(1)
      }
    }
  }

  if (config.fonts) {
    for (const [key, value] of Object.entries(config.fonts)) {
      if (!value || typeof value !== 'string' || value.trim() === '') {
        process.stderr.write(`Font name required for ${key}\n`)
        process.exit(1)
      }
    }
  }

  if (config.radius) {
    for (const [key, value] of Object.entries(config.radius)) {
      if (!value || typeof value !== 'string' || value.trim() === '') {
        process.stderr.write(`Radius value required for ${key}\n`)
        process.exit(1)
      }
    }
  }

  if (config.shadows) {
    for (const [key, value] of Object.entries(config.shadows)) {
      if (!value || typeof value !== 'string' || value.trim() === '') {
        process.stderr.write(`Shadow value required for ${key}\n`)
        process.exit(1)
      }
    }
  }
}

/**
 * Generates a CSS :root block with --theme-* custom properties from a config object.
 * @param {Record<string, any>} config
 * @param {string} themeName
 * @returns {string}
 */
function generateCSS(config, themeName) {
  const lines = []
  lines.push(`/* Auto-generated by scripts/generate-theme.mjs — DO NOT EDIT */`)
  lines.push(`/* Theme: ${themeName} */`)
  lines.push(`:root {`)

  if (config.colors) {
    for (const [key, value] of Object.entries(config.colors)) {
      lines.push(`  --theme-color-${key}: ${value};`)
    }
  }

  if (config.fonts) {
    for (const [key, value] of Object.entries(config.fonts)) {
      lines.push(`  --theme-font-${key}: ${value};`)
    }
  }

  if (config.radius) {
    for (const [key, value] of Object.entries(config.radius)) {
      lines.push(`  --theme-radius-${key}: ${value};`)
    }
  }

  if (config.shadows) {
    for (const [key, value] of Object.entries(config.shadows)) {
      lines.push(`  --theme-shadow-${key}: ${value};`)
    }
  }

  lines.push(`}`)
  return lines.join('\n') + '\n'
}

// --- Main ---

const themeName = process.env.NEXT_PUBLIC_THEME || 'default'
const themeDir = resolve(FRONTEND_ROOT, 'themes', themeName)
const defaultThemeDir = resolve(FRONTEND_ROOT, 'themes', 'default')
const outputPath = resolve(FRONTEND_ROOT, 'app', 'generated-theme.css')

// Load default config (always required as base)
const defaultYamlPath = resolve(defaultThemeDir, 'theme.yaml')
if (!existsSync(defaultYamlPath)) {
  process.stderr.write(`Default theme.yaml not found at: ${defaultYamlPath}\n`)
  process.exit(1)
}
const defaultConfig = parse(readFileSync(defaultYamlPath, 'utf-8'))

// Load shop config if different from default
let resolvedThemeName = themeName
let mergedConfig = defaultConfig

if (themeName !== 'default') {
  const shopYamlPath = resolve(themeDir, 'theme.yaml')

  if (existsSync(shopYamlPath)) {
    const shopConfig = parse(readFileSync(shopYamlPath, 'utf-8'))
    if (shopConfig && typeof shopConfig === 'object') {
      mergedConfig = deepMerge(defaultConfig, shopConfig)
    }
    resolvedThemeName = themeName
  } else {
    // Fallback: use default only
    process.stdout.write(`Theme "${themeName}" not found, falling back to default\n`)
    resolvedThemeName = 'default'
  }
}

validateConfig(mergedConfig)

const css = generateCSS(mergedConfig, resolvedThemeName)
writeFileSync(outputPath, css, 'utf-8')
process.stdout.write(`Theme generated: ${outputPath} (theme: ${resolvedThemeName})\n`)
