// scripts/generate-theme.mjs
import { readFileSync, writeFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { parse } from 'yaml'

const __dirname = dirname(fileURLToPath(import.meta.url))
const FRONTEND_ROOT = resolve(__dirname, '..')

const OKLCH_REGEX = /^oklch\(\s*[\d.]+\s+[\d.]+\s+[\d.]+(\s*\/\s*[\d.]+)?\s*\)$/

/**
 * Validates a theme config object.
 * Exits with code 1 and prints error message on first validation failure.
 * @param {Record<string, any>} config
 */
function validateConfig(config) {
  // Validate colors
  if (config.colors) {
    for (const [key, value] of Object.entries(config.colors)) {
      if (typeof value !== 'string' || !OKLCH_REGEX.test(value.trim())) {
        process.stderr.write(`Invalid color format for ${key}: expected oklch()\n`)
        process.exit(1)
      }
    }
  }

  // Validate fonts
  if (config.fonts) {
    for (const [key, value] of Object.entries(config.fonts)) {
      if (!value || typeof value !== 'string' || value.trim() === '') {
        process.stderr.write(`Font name required for ${key}\n`)
        process.exit(1)
      }
    }
  }

  // Validate radius
  if (config.radius) {
    for (const [key, value] of Object.entries(config.radius)) {
      if (!value || typeof value !== 'string' || value.trim() === '') {
        process.stderr.write(`Radius value required for ${key}\n`)
        process.exit(1)
      }
    }
  }

  // Validate shadows
  if (config.shadows) {
    for (const [key, value] of Object.entries(config.shadows)) {
      if (!value || typeof value !== 'string' || value.trim() === '') {
        process.stderr.write(`Shadow value required for ${key}\n`)
        process.exit(1)
      }
    }
  }
}

/**
 * Generates a CSS :root block with --theme-* custom properties from a config object.
 * @param {Record<string, any>} config
 * @param {string} themeName
 * @returns {string}
 */
function generateCSS(config, themeName) {
  const lines = []
  lines.push(`/* Auto-generated by scripts/generate-theme.mjs — DO NOT EDIT */`)
  lines.push(`/* Theme: ${themeName} */`)
  lines.push(`:root {`)

  if (config.colors) {
    for (const [key, value] of Object.entries(config.colors)) {
      lines.push(`  --theme-color-${key}: ${value};`)
    }
  }

  if (config.fonts) {
    for (const [key, value] of Object.entries(config.fonts)) {
      lines.push(`  --theme-font-${key}: ${value};`)
    }
  }

  if (config.radius) {
    for (const [key, value] of Object.entries(config.radius)) {
      lines.push(`  --theme-radius-${key}: ${value};`)
    }
  }

  if (config.shadows) {
    for (const [key, value] of Object.entries(config.shadows)) {
      lines.push(`  --theme-shadow-${key}: ${value};`)
    }
  }

  lines.push(`}`)
  return lines.join('\n') + '\n'
}

// --- Main ---

const themeName = process.env.NEXT_PUBLIC_THEME || 'default'
const themeDir = resolve(FRONTEND_ROOT, 'themes', themeName)
const defaultThemeDir = resolve(FRONTEND_ROOT, 'themes', 'default')
const outputPath = resolve(FRONTEND_ROOT, 'app', 'generated-theme.css')

// Determine which theme.yaml to load — fallback to default if theme folder does not exist
let resolvedThemeDir = themeDir
if (!existsSync(resolve(themeDir, 'theme.yaml'))) {
  resolvedThemeDir = defaultThemeDir
}

const yamlPath = resolve(resolvedThemeDir, 'theme.yaml')
const yamlContent = readFileSync(yamlPath, 'utf-8')
const config = parse(yamlContent)

validateConfig(config)

const resolvedThemeName = resolvedThemeDir === defaultThemeDir ? 'default' : themeName
const css = generateCSS(config, resolvedThemeName)

writeFileSync(outputPath, css, 'utf-8')
process.stdout.write(`Theme generated: ${outputPath} (theme: ${resolvedThemeName})\n`)
