// tests/slices/frontend-theming/slice-01-theme-token-system.test.ts
import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { readFileSync, writeFileSync, existsSync, unlinkSync, mkdirSync, rmSync } from 'fs'
import { resolve } from 'path'
import { execSync } from 'child_process'

const FRONTEND_ROOT = resolve(__dirname, '..', '..', '..')
const GENERATED_CSS = resolve(FRONTEND_ROOT, 'app/generated-theme.css')
const SCRIPT_PATH = resolve(FRONTEND_ROOT, 'scripts/generate-theme.mjs')
const DEFAULT_THEME = resolve(FRONTEND_ROOT, 'themes/default/theme.yaml')

describe('Theme Token System — generate-theme.mjs', () => {
  afterEach(() => {
    // Cleanup: generated-theme.css nach jedem Test löschen
    if (existsSync(GENERATED_CSS)) {
      unlinkSync(GENERATED_CSS)
    }
  })

  describe('Script existiert', () => {
    it('should have generate-theme.mjs in frontend/scripts/', () => {
      expect(existsSync(SCRIPT_PATH)).toBe(true)
    })

    it('should have themes/default/theme.yaml', () => {
      expect(existsSync(DEFAULT_THEME)).toBe(true)
    })
  })

  describe('Erfolgreiche CSS-Generierung', () => {
    it('should generate app/generated-theme.css when no NEXT_PUBLIC_THEME is set', () => {
      execSync(`node ${SCRIPT_PATH}`, { cwd: FRONTEND_ROOT, env: { ...process.env, NEXT_PUBLIC_THEME: '' } })
      expect(existsSync(GENERATED_CSS)).toBe(true)
    })

    it('should include all required color tokens in generated CSS', () => {
      execSync(`node ${SCRIPT_PATH}`, { cwd: FRONTEND_ROOT })
      const css = readFileSync(GENERATED_CSS, 'utf-8')
      expect(css).toContain('--theme-color-primary')
      expect(css).toContain('--theme-color-primary-hover')
      expect(css).toContain('--theme-color-accent')
      expect(css).toContain('--theme-color-surface')
      expect(css).toContain('--theme-color-surface-elevated')
      expect(css).toContain('--theme-color-text-primary')
      expect(css).toContain('--theme-color-text-secondary')
      expect(css).toContain('--theme-color-border')
    })

    it('should include new status color tokens (error, success, warning)', () => {
      execSync(`node ${SCRIPT_PATH}`, { cwd: FRONTEND_ROOT })
      const css = readFileSync(GENERATED_CSS, 'utf-8')
      expect(css).toContain('--theme-color-error: oklch(0.55 0.2 25)')
      expect(css).toContain('--theme-color-success: oklch(0.55 0.15 145)')
      expect(css).toContain('--theme-color-warning: oklch(0.7 0.15 85)')
    })

    it('should include overlay token with alpha channel', () => {
      execSync(`node ${SCRIPT_PATH}`, { cwd: FRONTEND_ROOT })
      const css = readFileSync(GENERATED_CSS, 'utf-8')
      expect(css).toContain('--theme-color-overlay: oklch(0 0 0 / 0.5)')
    })

    it('should include radius tokens', () => {
      execSync(`node ${SCRIPT_PATH}`, { cwd: FRONTEND_ROOT })
      const css = readFileSync(GENERATED_CSS, 'utf-8')
      expect(css).toContain('--theme-radius-card: 0.75rem')
      expect(css).toContain('--theme-radius-button: 0.5rem')
    })

    it('should include shadow tokens', () => {
      execSync(`node ${SCRIPT_PATH}`, { cwd: FRONTEND_ROOT })
      const css = readFileSync(GENERATED_CSS, 'utf-8')
      expect(css).toContain('--theme-shadow-card:')
      expect(css).toContain('--theme-shadow-card-hover:')
    })

    it('should include font tokens', () => {
      execSync(`node ${SCRIPT_PATH}`, { cwd: FRONTEND_ROOT })
      const css = readFileSync(GENERATED_CSS, 'utf-8')
      expect(css).toContain('--theme-font-heading: Inter')
      expect(css).toContain('--theme-font-body: Inter')
    })

    it('should wrap all tokens in :root block', () => {
      execSync(`node ${SCRIPT_PATH}`, { cwd: FRONTEND_ROOT })
      const css = readFileSync(GENERATED_CSS, 'utf-8')
      expect(css).toContain(':root {')
      expect(css).toContain('}')
    })

    it('should include auto-generated comment header', () => {
      execSync(`node ${SCRIPT_PATH}`, { cwd: FRONTEND_ROOT })
      const css = readFileSync(GENERATED_CSS, 'utf-8')
      expect(css).toContain('Auto-generated by scripts/generate-theme.mjs')
    })
  })

  describe('YAML-Validierung — Farbformat', () => {
    it('should exit with code 1 when color is not oklch format', () => {
      // Temporäres kaputtes theme.yaml
      const invalidYaml = `
colors:
  primary: "#FF0000"
  error: "oklch(0.55 0.2 25)"
fonts:
  heading: "Inter"
  body: "Inter"
radius:
  card: "0.75rem"
  button: "0.5rem"
shadows:
  card: "0 1px 3px oklch(0 0 0 / 0.08)"
  card-hover: "0 8px 25px oklch(0 0 0 / 0.12)"
`
      const tempThemeDir = resolve(FRONTEND_ROOT, 'themes/__test_invalid__')
      mkdirSync(tempThemeDir, { recursive: true })
      writeFileSync(resolve(tempThemeDir, 'theme.yaml'), invalidYaml)

      let exitCode: number | null = null
      let errorOutput = ''
      try {
        execSync(`node ${SCRIPT_PATH}`, {
          cwd: FRONTEND_ROOT,
          env: { ...process.env, NEXT_PUBLIC_THEME: '__test_invalid__' }
        })
      } catch (err: any) {
        exitCode = err.status
        errorOutput = err.stderr?.toString() ?? ''
      } finally {
        // Cleanup
        rmSync(tempThemeDir, { recursive: true, force: true })
      }

      expect(exitCode).toBe(1)
      expect(errorOutput).toContain('Invalid color format for primary')
    })

    it('should exit with code 1 when font name is empty', () => {
      const invalidYaml = `
colors:
  primary: "oklch(0.45 0.2 270)"
  error: "oklch(0.55 0.2 25)"
  success: "oklch(0.55 0.15 145)"
  warning: "oklch(0.7 0.15 85)"
  overlay: "oklch(0 0 0 / 0.5)"
fonts:
  heading: ""
  body: "Inter"
radius:
  card: "0.75rem"
  button: "0.5rem"
shadows:
  card: "0 1px 3px oklch(0 0 0 / 0.08)"
  card-hover: "0 8px 25px oklch(0 0 0 / 0.12)"
`
      const tempThemeDir = resolve(FRONTEND_ROOT, 'themes/__test_empty_font__')
      mkdirSync(tempThemeDir, { recursive: true })
      writeFileSync(resolve(tempThemeDir, 'theme.yaml'), invalidYaml)

      let exitCode: number | null = null
      let errorOutput = ''
      try {
        execSync(`node ${SCRIPT_PATH}`, {
          cwd: FRONTEND_ROOT,
          env: { ...process.env, NEXT_PUBLIC_THEME: '__test_empty_font__' }
        })
      } catch (err: any) {
        exitCode = err.status
        errorOutput = err.stderr?.toString() ?? ''
      } finally {
        rmSync(tempThemeDir, { recursive: true, force: true })
      }

      expect(exitCode).toBe(1)
      expect(errorOutput).toContain('Font name required for heading')
    })
  })

  describe('Fallback auf Default-Theme', () => {
    it('should fall back to default theme when NEXT_PUBLIC_THEME folder does not exist', () => {
      // Nicht-existierendes Theme angeben
      execSync(`node ${SCRIPT_PATH}`, {
        cwd: FRONTEND_ROOT,
        env: { ...process.env, NEXT_PUBLIC_THEME: 'non-existent-shop-xyz' }
      })
      // Soll trotzdem generieren (Fallback auf default)
      expect(existsSync(GENERATED_CSS)).toBe(true)
    })
  })
})

describe('cn() Utility', () => {
  it('should exist in lib/utils.ts', async () => {
    const { cn } = await import('@/lib/utils')
    expect(typeof cn).toBe('function')
  })

  it('should merge class names correctly', async () => {
    const { cn } = await import('@/lib/utils')
    const result = cn('bg-primary', 'text-white')
    expect(result).toBe('bg-primary text-white')
  })

  it('should resolve tailwind conflicts (last wins)', async () => {
    const { cn } = await import('@/lib/utils')
    const result = cn('bg-primary', 'bg-error')
    // tailwind-merge: bg-error gewinnt (letzter Wert)
    expect(result).toBe('bg-error')
  })

  it('should handle conditional classes', async () => {
    const { cn } = await import('@/lib/utils')
    const isActive = true
    const result = cn('base-class', isActive && 'active-class', !isActive && 'inactive-class')
    expect(result).toBe('base-class active-class')
  })

  it('should handle undefined and null values', async () => {
    const { cn } = await import('@/lib/utils')
    const result = cn('base', undefined, null, false, 'end')
    expect(result).toBe('base end')
  })
})

describe('globals.css — Token Registration', () => {
  const globalsPath = resolve(FRONTEND_ROOT, 'app/globals.css')

  it('should import generated-theme.css', () => {
    const css = readFileSync(globalsPath, 'utf-8')
    expect(css).toContain('@import "./generated-theme.css"')
  })

  it('should NOT contain [data-theme] blocks anymore', () => {
    const css = readFileSync(globalsPath, 'utf-8')
    expect(css).not.toContain('[data-theme=')
  })

  it('should register --color-error in @theme block', () => {
    const css = readFileSync(globalsPath, 'utf-8')
    expect(css).toContain('--color-error')
  })

  it('should register --color-success in @theme block', () => {
    const css = readFileSync(globalsPath, 'utf-8')
    expect(css).toContain('--color-success')
  })

  it('should register --color-warning in @theme block', () => {
    const css = readFileSync(globalsPath, 'utf-8')
    expect(css).toContain('--color-warning')
  })

  it('should register --color-overlay in @theme block', () => {
    const css = readFileSync(globalsPath, 'utf-8')
    expect(css).toContain('--color-overlay')
  })

  it('should register --radius-card in @theme block', () => {
    const css = readFileSync(globalsPath, 'utf-8')
    expect(css).toContain('--radius-card')
  })

  it('should register --radius-button in @theme block', () => {
    const css = readFileSync(globalsPath, 'utf-8')
    expect(css).toContain('--radius-button')
  })

  it('should register --shadow-card in @theme block', () => {
    const css = readFileSync(globalsPath, 'utf-8')
    expect(css).toContain('--shadow-card')
  })

  it('should register --shadow-card-hover in @theme block', () => {
    const css = readFileSync(globalsPath, 'utf-8')
    expect(css).toContain('--shadow-card-hover')
  })
})

describe('theme.yaml — Default Schema', () => {
  it('should have all required color keys', async () => {
    const { parse } = await import('yaml')
    const content = readFileSync(DEFAULT_THEME, 'utf-8')
    const config = parse(content)
    const requiredColors = [
      'primary', 'primary-hover', 'accent', 'surface', 'surface-elevated',
      'text-primary', 'text-secondary', 'border',
      'error', 'success', 'warning', 'overlay'
    ]
    for (const key of requiredColors) {
      expect(config.colors[key], `Missing color: ${key}`).toBeDefined()
      expect(config.colors[key], `Empty color: ${key}`).not.toBe('')
    }
  })

  it('should have all colors in oklch format', async () => {
    const { parse } = await import('yaml')
    const content = readFileSync(DEFAULT_THEME, 'utf-8')
    const config = parse(content)
    const oklchRegex = /^oklch\(\s*[\d.]+\s+[\d.]+\s+[\d.]+(\s*\/\s*[\d.]+)?\s*\)$/
    for (const [key, value] of Object.entries(config.colors as Record<string, string>)) {
      expect(oklchRegex.test(value), `Color "${key}" is not in oklch format: "${value}"`).toBe(true)
    }
  })

  it('should have fonts.heading and fonts.body defined and non-empty', async () => {
    const { parse } = await import('yaml')
    const content = readFileSync(DEFAULT_THEME, 'utf-8')
    const config = parse(content)
    expect(config.fonts?.heading).toBeTruthy()
    expect(config.fonts?.body).toBeTruthy()
  })

  it('should have radius.card and radius.button defined', async () => {
    const { parse } = await import('yaml')
    const content = readFileSync(DEFAULT_THEME, 'utf-8')
    const config = parse(content)
    expect(config.radius?.card).toBeTruthy()
    expect(config.radius?.button).toBeTruthy()
  })

  it('should have shadows.card and shadows.card-hover defined', async () => {
    const { parse } = await import('yaml')
    const content = readFileSync(DEFAULT_THEME, 'utf-8')
    const config = parse(content)
    expect(config.shadows?.card).toBeTruthy()
    expect(config.shadows?.['card-hover']).toBeTruthy()
  })
})
