<?php
/**
 * Plugin bootstrap entry-point.
 *
 * Wires hooks and exposes the plugin file path to follow-up slices
 * (HPOS declare in slice-03, schema/dbDelta in slice-04, options-defaults
 * in slice-05, i18n textdomain in slice-06, and beyond).
 *
 * @package SpreadconnectPod\Bootstrap
 */

declare(strict_types=1);

namespace SpreadconnectPod\Bootstrap;

use Automattic\WooCommerce\Utilities\FeaturesUtil;
use SpreadconnectPod\Catalog\AttributeProvisioner;
use SpreadconnectPod\Catalog\SyncArticleJob;

/**
 * Central bootstrap for the Spreadconnect POD plugin.
 *
 * Idempotent: subsequent calls to {@see self::init()} are no-ops once the
 * skeleton has been wired the first time. Future slices will add hook
 * registrations to this class, all of which must remain idempotent under
 * the same guard.
 */
final class Plugin
{
	/**
	 * Whether {@see self::init()} has already executed.
	 */
	private static bool $initialized = false;

	/**
	 * Absolute path to the main plugin file (`spreadconnect-pod.php`).
	 *
	 * Stored on first invocation so that follow-up slices can resolve the
	 * file for `FeaturesUtil::declare_compatibility()` (slice-03),
	 * `plugin_basename()` for i18n (slice-06), `register_activation_hook()`
	 * (slice-04/05) and similar lifecycle helpers.
	 */
	private static string $pluginFile = '';

	/**
	 * Bootstrap the plugin.
	 *
	 * Called from `spreadconnect-pod.php` on file include.
	 *
	 * Idempotency: re-entrant calls return early without re-registering
	 * hooks. This protects against double-includes (e.g. a misconfigured
	 * `must-use` shim) and ensures `_doing_it_wrong` notices never fire.
	 *
	 * @param string $plugin_file Absolute path to the main plugin file
	 *                            (typically `__FILE__` from
	 *                            `spreadconnect-pod.php`).
	 */
	public static function init( string $plugin_file ): void
	{
		if ( self::$initialized ) {
			return;
		}

		self::$initialized = true;
		self::$pluginFile  = $plugin_file;

		// Hook registrations.
		//
		// Follow-up slices will extend this method:
		//   - slice-04: `register_activation_hook()` -> Schema::dbDelta().
		//   - slice-05: Options defaults via activation hook.
		//   - slice-06: `plugins_loaded` -> load_plugin_textdomain().
		//   - slice-09+: REST routes, webhook controller, AS handlers, etc.

		// slice-03: Declare HPOS (Custom Order Tables) compatibility before
		// WooCommerce initialises its feature flags. Must run inside the
		// idempotency guard so duplicate `init()` calls cannot register the
		// listener twice (`add_action` does not dedupe static-method callables
		// on identical classes).
		add_action( 'before_woocommerce_init', [ self::class, 'declareHposCompatibility' ] );

		// slice-04: Register the schema installer on plugin activation. The
		// activation hook fires once per activation event; together with the
		// idempotency guard above it stays exactly-once per `init()` run.
		// `dbDelta()` itself is additive-only, so re-activating the plugin
		// is safe and never destroys existing rows.
		register_activation_hook( $plugin_file, [ Schema::class, 'install' ] );

		// slice-05: Seed the 18 explicit `spreadconnect_*` options on
		// activation. `OptionsDefaults::install()` is idempotent (uses
		// `add_option()`, which never overwrites existing values), so
		// re-activating the plugin preserves any admin-customised values.
		// The 19th option `spreadconnect_webhook_secret` is generated by
		// slice-14, not seeded here.
		register_activation_hook( $plugin_file, [ OptionsDefaults::class, 'install' ] );

		// slice-20: Provision the `pa_groesse` / `pa_farbe` WC attribute
		// taxonomies on activation. `AttributeProvisioner::ensure()` is
		// idempotent — pre-existing taxonomies are skipped without
		// modification, and only missing slugs trigger `wc_create_attribute()`.
		// The static-property guard above ensures this hook is registered
		// exactly once per `init()` run, preserving slice-02 AC-5 idempotency.
		register_activation_hook( $plugin_file, [ AttributeProvisioner::class, 'ensure' ] );

		// slice-06: Load the `spreadconnect-pod` text-domain on
		// `plugins_loaded` (WP-default priority 10). The hook fires once per
		// request, after WP has finalised the locale, which is the earliest
		// safe point to call `load_plugin_textdomain()`. Idempotency is
		// guaranteed by the `self::$initialized` guard above: the action is
		// registered exactly once per request, so the callback fires at most
		// once per request and `.mo` files are never loaded twice.
		add_action(
			'plugins_loaded',
			static function () use ( $plugin_file ): void {
				load_plugin_textdomain(
					'spreadconnect-pod',
					false,
					dirname( plugin_basename( $plugin_file ) ) . '/languages'
				);
			}
		);

		// slice-23: Register the per-article sync hook handler. Action-
		// Scheduler dispatches `spreadconnect/sync_article` with the args-
		// array as the first parameter; the static bridge resolves the
		// production-default collaborator chain (SpreadconnectClient,
		// ImageSideloader, ProductMapper, SyncHistoryRepo) and invokes
		// `handle()`. The hook is registered with priority 10 and exactly
		// one accepted argument (the args-array), per AS conventions.
		// Producer-side `as_enqueue_async_action()` calls live in slice-24
		// (catalog-job), slice-25 (article webhooks) and slice-34 (re-sync
		// button) — slice-23 is the consumer only.
		add_action(
			'spreadconnect/sync_article',
			[ SyncArticleJob::class, 'handleStatic' ],
			10,
			1
		);
	}

	/**
	 * Declare HPOS (Custom Order Tables) compatibility with WooCommerce.
	 *
	 * Hooked to `before_woocommerce_init`. Guarded by `class_exists()` so the
	 * callback is a safe no-op when WooCommerce is inactive or its
	 * `FeaturesUtil` helper has not been loaded yet (e.g. very old WC
	 * versions).
	 *
	 * @return void
	 */
	public static function declareHposCompatibility(): void
	{
		if ( ! class_exists( FeaturesUtil::class ) ) {
			return;
		}

		FeaturesUtil::declare_compatibility(
			'custom_order_tables',
			self::pluginFile(),
			true
		);
	}

	/**
	 * Return the absolute path to the main plugin file.
	 *
	 * Consumers (slice-03+) call this to obtain the value originally passed
	 * to {@see self::init()} without having to track `__FILE__` themselves.
	 */
	public static function pluginFile(): string
	{
		return self::$pluginFile;
	}
}
